My tools build scripts

This Repository contains scripts for building tools used by me

* Layout
  All tools are installed within _HOME_ directory.
  because _HOME_ directory is usually mount through NFS on different
  machines, architecture and operating system, then there are couple
  assumptions where apps are installed.

** Installation
   - ROOT directory for packages installations is _${HOME}/tools/pkgs_
   - Each package is configured and installed in its own independent directory
     - packages directory are named as _<PKG>-<VERSION>-<OSRELEASE>-<HOSTTYPE>_
       + PKG:: package name
       + VERSION:: package version
       + OSRELEASE:: easily distinguished OS on which package is targeted (eg. Tikanga for RHEL5, Santiago for RHEL6)
       + HOSTTYPE:: architecture for which package is targeted (e.g. x86_64, i686)

** Deployment
   All apps are deployed by GNU stow tool.
   All paths (PATH,LD_LIBRARY_PATH,MANPATH. etc.) are configured in runtime by shell login configuration (.bashrc).
   Deployment path is configured as =${TOOLSPATH}= environment variable and is put in =${HOME}/tools/<OSRELEASE>-<HOSTTYPE>=.

